# Form implementation generated from reading ui file 'caluclator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton, QLabel, QMenuBar, QMenu, QStatusBar
import sys
 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 759)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('4'))
        self.pushButton_3.setGeometry(QtCore.QRect(130, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('2'))
        self.pushButton_2.setGeometry(QtCore.QRect(210, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('5'))
        self.pushButton_6.setGeometry(QtCore.QRect(210, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('3'))
        self.pushButton_8.setGeometry(QtCore.QRect(290, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('6'))
        self.pushButton_9.setGeometry(QtCore.QRect(290, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(370, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(370, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(370, 350, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 240, 51, 51))
        self.label_5.setObjectName("label_5")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('7'))
        self.pushButton_16.setGeometry(QtCore.QRect(130, 430, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('9'))
        self.pushButton_17.setGeometry(QtCore.QRect(290, 430, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('8'))
        self.pushButton_18.setGeometry(QtCore.QRect(210, 430, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(370, 430, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('1'))
        self.pushButton.setGeometry(QtCore.QRect(130, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('0'))
        self.pushButton_20.setGeometry(QtCore.QRect(130, 510, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.press_it('.'))
        self.pushButton_21.setGeometry(QtCore.QRect(290, 510, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(210, 510, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(370, 510, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 60, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("background:rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 36))
        self.menubar.setObjectName("menubar")
        self.menucalculator = QtWidgets.QMenu(parent=self.menubar)
        self.menucalculator.setObjectName("menucalculator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menucalculator.menuAction())

        self.retranslateUi(MainWindow)
        self.connect_actions()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "4"))
        self.pushButton_4.setText(_translate("MainWindow", "AC"))
        self.pushButton_5.setText(_translate("MainWindow", "()"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "%"))
        self.pushButton_8.setText(_translate("MainWindow", "3"))
        self.pushButton_9.setText(_translate("MainWindow", "6"))
        self.pushButton_13.setText(_translate("MainWindow", "/"))
        self.pushButton_14.setText(_translate("MainWindow", "*"))
        self.pushButton_15.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "1"))
        self.pushButton_16.setText(_translate("MainWindow", "7"))
        self.pushButton_17.setText(_translate("MainWindow", "9"))
        self.pushButton_18.setText(_translate("MainWindow", "8"))
        self.pushButton_19.setText(_translate("MainWindow", "+"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.pushButton_20.setText(_translate("MainWindow", "0"))
        self.pushButton_21.setText(_translate("MainWindow", "."))
        self.pushButton_22.setText(_translate("MainWindow", "x"))
        self.pushButton_23.setText(_translate("MainWindow", "="))
        self.label.setText(_translate("MainWindow", "0"))
        self.menucalculator.setTitle(_translate("MainWindow", "calculator"))
    

    def press_it(self, pressed):
        current_text = self.label.text()
        if current_text == "0":
            self.label.setText(pressed)
        else:
            self.label.setText(current_text + pressed)
    
            
    def connect_actions(self):
        self.pushButton_7.clicked.connect(self.percent)
        self.pushButton_5.clicked.connect(self.bracket)
        self.pushButton_4.clicked.connect(self.clear)
        self.pushButton_19.clicked.connect(self.add)
        self.pushButton_15.clicked.connect(self.sub)
        self.pushButton_13.clicked.connect(self.div)
        self.pushButton_14.clicked.connect(self.multi)
        self.pushButton_22.clicked.connect(self.delete)
        self.pushButton_23.clicked.connect(self.equal)


    def equal(self):
        equation = self.label.text()
        try:
            ans = eval(equation)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")

    def bracket(self):
        text = self.label.text()
        if text.count('(') > text.count(')'):
            self.label.setText(f'{text})')
        else:
            self.label.setText(f'{text}(')

    def add(self):
        text = self.label.text()
        self.label.setText(text + '+')

    def sub(self):
        text = self.label.text()
        self.label.setText(text + '-')

    def multi(self):
        text = self.label.text()
        self.label.setText(text + '*')

    def div(self):
        text = self.label.text()
        self.label.setText(text + '/')

    def n1(self):
        text = self.label.text()
        self.label.setText(text + '1')

    def n2(self):
        text = self.label.text()
        self.label.setText(text + '2')

    def n3(self):
        text = self.label.text()
        self.label.setText(text + '3')

    def n4(self):
        text = self.label.text()
        self.label.setText(text + '4')

    def n5(self):
        text = self.label.text()
        self.label.setText(text + '5')

    def n6(self):
        text = self.label.text()
        self.label.setText(text + '6')

    def n7(self):
        text = self.label.text()
        self.label.setText(text + '7')

    def n8(self):
        text = self.label.text()
        self.label.setText(text + '8')

    def n9(self):
        text = self.label.text()
        self.label.setText(text + '9')

    def n0(self):
        text = self.label.text()
        self.label.setText(text + '0')

    def percent(self):
        text = self.label.text()
        self.label.setText(text + '%')
    
    def dot(self):
        text = self.label.text()
        self.label.setText(text + '.')

    def clear(self):
        self.label.setText("0")

    def delete(self):
        text =self.label.text()
        print(text[:len(text)-1])
        self.label.setText(text[:len(text)-1])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    try:
        sys.exit(app.exec())
    except:
        print('Closing Window...')